name: Integration Request
description: >
  Request Integration
title: "[Integration Request]: "
labels: ["integration"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time and creating a new integration request!
  - type: dropdown
    id: integrationType
    attributes:
      label: Integration Type
      description: What kind of integration are you requesting for?
      options:
        - Protocol/dAPP Integration
        - Network Integration
        - ASP Integration
        - Webapp Integration
      default: 0
    validations:
      required: true
  - type: textarea
    id: integrationTarget
    attributes:
      label: Integration Target
      description: What is the name of the system you are requesting integration for?
  - type: dropdown
    id: involvementType
    attributes:
      label: Involvement
      description: What is your involvement?
      options:
        - Founder / CTO
        - Developer / Engineer
        - Product Manager
        - Community Member
      default: 0
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or twitter handle @example
    validations:
      required: false
  - type: textarea
    id: ideas
    attributes:
      label: Integration Details
      description: Let us know the details !
